Autoservice/mysite/autoservice/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.cars, name='cars'),
    path('cars/<int:car_id>', views.car, name='car'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name='order_details'),
    path('search/', views.search, name='search'),
    path('myorders/', views.OrdersByUserListView.as_view(), name='my_orders'),
    path('register/', views.register, name='register')
]



Autoservice/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('autoservice/', include('autoservice.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))





Autoservice/mysite/autoservice/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from django.db.models import Sum


class CarModel(models.Model):
    car_brand = models.CharField('Brand', max_length=100, null=False)
    car_model = models.CharField('Model', max_length=100, null=False)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.car_brand} {self.car_model}'

    class Meta:
        verbose_name = 'Car Model'
        verbose_name_plural = 'Car Models'


class Car(models.Model):
    country_registration_no = models.CharField('Country registration number', max_length=100, null=False)
    car_model = models.ForeignKey(CarModel, on_delete=models.PROTECT, null=False)
    vin_code = models.CharField('VIN', max_length=100)
    client = models.CharField('Client\'s full name',
                              max_length=100,
                              null=False,
                              help_text='Client name and surname')
    car_photo = models.ImageField('Car Photo', upload_to='car_photos', null=True)
    description = HTMLField(null=True)


    def __str__(self):
        return f'{self.country_registration_no} {self.car_model} {self.vin_code}'

    class Meta:
        verbose_name = 'Car'
        verbose_name_plural = 'Cars'

    def get_absolute_url(self):
        return reverse('car-detail', args=[str(self.id)])


class Service(models.Model):
    service_name = models.CharField('Service name', max_length=100, null=False)
    price = models.FloatField('Price', null=False)

    def get_absolute_url(self):
        return reverse('service-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.service_name}'

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class OrderQuerySet(models.QuerySet):
    def orders_in_progress(self):
        return self.filter(status__exact='p')

    def order_by_due_date(self):
        return self.order_by('due_back')


class Order(models.Model):
    objects = OrderQuerySet.as_manager()
    order_date = models.DateField('Order Date', null=False)
    car = models.ForeignKey(Car, on_delete=models.PROTECT, null=False)
    order_amount = models.FloatField('Order Amount', null=False)
    due_back = models.DateField('Car will be returned', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    ORDER_STATUS = (
        ('p', 'processing'),
        ('c', 'completed'),
        ('r', 'rejected'),
    )

    status = models.CharField(
        max_length=1,
        choices=ORDER_STATUS,
        blank=True,
        default='p',
        help_text='Order status',
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    @property
    def get_total_order_amount(self):
        orderlines = OrderLine.objects.filter(order_id=self.id)
        total_amount = 0
        for line in orderlines:
            total_amount += line.quantity * line.price
        print(line.quantity)
        print(type(total_amount))
        self.order_amount = total_amount
        self.save()


    class Meta:
        ordering = ['order_date']

    def __str__(self):
        return f'{self.id} ({self.order_date}) ({self.car.car_model}) ({self.car.car_model})'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def display_service(self):
        return ', '.join(orderlines.service.service_name for orderlines in self.orderlines.all())

    display_service.short_description = 'Service'

    def display_quantity(self):
        return ', '.join(str(orderlines.quantity) for orderlines in self.orderlines.all())

    display_quantity.short_description = 'Quantity'

    def display_price(self):
        return ', '.join(str(orderlines.price) for orderlines in self.orderlines.all())

    display_price.short_description = 'Price'


class OrderLine(models.Model):
    service = models.ForeignKey(Service, on_delete=models.PROTECT, null=False)
    order = models.ForeignKey(Order, on_delete=models.PROTECT, null=False, related_name='orderlines')
    quantity = models.IntegerField('Quantity', null=True)
    price = models.FloatField('Price', null=False)

    def __str__(self):
        return f'{self.id} {self.service.service_name} {self.quantity} {self.price}'

    class Meta:
        verbose_name = 'Order Line'
        verbose_name_plural = 'Order Lines'


class ClientReview(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)

Autoservice/mysite/autoservice/forms.py
from .models import ClientReview
from django import forms


class ClientReviewForm(forms.ModelForm):
    class Meta:
        model = ClientReview
        fields = ('content', 'order', 'reviewer',)
        widgets = {'order': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

Autoservice/mysite/autoservice/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Car, Service, Order, OrderLine
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, reverse
from .forms import ClientReviewForm
from django.views.generic.edit import FormMixin


def index(request):
    services = Service.objects.all()
    service_count = services.count()
    cars = Car.objects.all()
    car_count = cars.count()

    # Laisvos knygos (tos, kurios turi statusą 'g')
    completed_orders_count = Order.objects.filter(status__exact='p').count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1


    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'service_count': service_count,
        'car_count': car_count,
        'completed_orders_count': completed_orders_count,
        'num_visits': num_visits,
    }

    response = render(request, 'index.html', context=context)
    return response


def cars(request):
    paginator = Paginator(Car.objects.all(), 1)
    page_number = request.GET.get('page')
    cars = paginator.get_page(page_number)
    context = {
        'cars': cars
    }
    response = render(request, 'cars.html', context=context)
    return response


def car(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    response = render(request, 'car.html', {'car': car})
    return response


class OrderListView(generic.ListView):
    model = Order
    paginate_by = 1
    context_object_name = 'order_list'
    template_name = 'order_list.html'

    def get_queryset(self):
        orders = Order.objects.filter(status='p')
        return orders


class OrdersByUserListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'my_orders.html'
    paginate_by = 5

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).orders_in_progress().order_by_due_date()


class OrderDetailView(FormMixin, generic.DetailView):
    model = Order
    template_name = 'order_detail.html'
    form_class = ClientReviewForm

    class Meta:
        ordering = ['order_date']

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('order_details', kwargs={'pk': self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)


def search(request):
    query = request.GET.get('query')
    search_results = Car.objects.filter(Q(client__icontains=query) | Q(car_model__car_brand__icontains=query)
                                        | Q(country_registration_no__icontains=query) | Q(vin_code__icontains=query) \
                                        | Q(car_model__car_model__icontains=query))
    return render(request, 'search.html', {'cars': search_results, 'query': query})


@csrf_protect
def register(request):
    error_message = None
    if request.method != "POST":
        return render(request, 'register.html')

    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    password2 = request.POST['password2']

    if password != password2:
        error_message = 'Passwords do not match!'
    elif User.objects.filter(username=username).exists():
        error_message = f'User name {username} already exists'
    elif User.objects.filter(email=email).exists():
        error_message = f'User email {email} already exists'

    if error_message:
        messages.error(request, error_message)
        return redirect('register')

    User.objects.create_user(username=username, email=email, password=password)

    return render(request, 'register.html')

Autoservice/mysite/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Autoservice</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

      {% block sidebar %}
        <ul class="sidebar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="#">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my_orders'%}">My Orders</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/autoservice">Log Out</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Log In</a></li>
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Register</a></li>
          {% endif %}
          <li><a href="{% url 'index' %}">Start</a></li>
          <li><a href="{% url 'cars' %}">Cars</a></li>
          <li><a href="{% url 'orders' %}">Orders</a></li>
          <li>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <input name="query" class="form-control" type="text" placeholder="Search">
          </form>
        </li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
          integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
          crossorigin="anonymous"></script>

</body>
</html>

Autoservice/mysite/autoservice/templates/car.html
{% extends "base.html" %}

{% block content %}
    <hr class="container car">
    <h4>{{ car.car_model }}</h4>
    <hr/>
    <h1>Car details:</h1>
    <img src="{{ car.car_photo.url }}" style="margin-bottom: 20px;">
    </hr>
        <p><strong>Owner:</strong> {{ car.client }}</p>
        <p><strong>Country Code:</strong> {{ car.country_registration_no }}</p>
        <p><strong>VIN:</strong> {{ car.vin_code }}</p>
        <p>{{ car.description | safe }}</p>
    </div>
{% endblock %}

Autoservice/mysite/autoservice/templates/cars.html
{% extends "base.html" %}

{% block content %}
 {% load static %}
    <h1>Cars</h1></br>
    {% if cars %}
    <div class="row">
      {% for car in cars %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if car.car_photo %}
              <img src="{{ car.car_photo.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{ car.id }}">{{ car.car_model }}</a></h6>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>There are no cars to show</p>
    {% endif %}
<div class="container pages">
    <nav aria-label="...">
        {% if cars.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in cars.paginator.page_range %}
                    {% if cars.number == i %}
                        <li class="page-item active">
                            <a class="page-link href">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>

{% endblock %}

Autoservice/mysite/autoservice/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Autoservice</h1>
  <p>Welcome to our page!</p>
  <p>We offer:</p>
  <ul>
    <li><strong>Services:</strong> {{ service_count }}</li>
    <li><strong>Cars:</strong> {{ car_count }}</li>
    <li><strong>Orders we have completed:</strong> {{ completed_orders_count }}</li>
  </ul>
  <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

Autoservice/mysite/autoservice/templates/my_orders.html
{% extends "base.html" %}

{% block content %}
    <h1>My Orders</h1>

    {% if order_list %}
    <ul>

      {% for order in order_list %}
      <li class="{% if order.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'order_details' order.pk %}">{{order.order_date}}</a> ({{ order.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Currently you have no orders</p>
    {% endif %}       
{% endblock %}

Autoservice/mysite/autoservice/templates/order_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>ORDER ID: {{ order.id }}</h1>

  <p><strong>Order Date:</strong> {{ order.order_date }}</p>
  <p><strong>Car Model:</strong> {{ order.car.car_model }}</p>
  <p><strong>Order Amount:</strong> {{ order.order_amount }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Order details:</h4>
    {% for order_line in order.orderlines.all %}
      <hr>
    <p><strong>Service:</strong> {{ order_line.service }} </p>
    <p><strong>Quantity:</strong> {{ order_line.quantity }} </p>
    <p> <strong>Price:</strong> {{ order_line.price }}</p>
    {% endfor %}
    </br>
  <h4>Reviews:</h4>
  {% if order.clientreview_set.all %}
    {% for review in order.clientreview_set.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>No reviews</p>
  {% endif %}
      {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Leave a review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Save">
    </form>
  </div>
  {% endif %}

  </div>
{% endblock %}

Autoservice/mysite/autoservice/templates/order_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Order list:</h1>
  {% if order_list %}
  <ul>
    {% for order in order_list %}
      <li>
        <a href="{{ order.id }}">{{order.order_date}} {{ order.car.car_model }}</a> ({{order.order_amount}} EUR)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no orders to display</p>
  {% endif %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

Autoservice/mysite/autoservice/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>User Registration</h3><br/>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">User Name</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Up to 150 symbols</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Will not be shared with anyone. No spam.
                    Required for a new password </small>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Not less than 8 symbols. Not only numbers</small>
            </div>
            <div class="form-group">
                <label for="password2">Confirm password</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Register</button>
        </form>
        <p>If you have registered earlier, <a href="{% url 'login'%}?next={{request.path}}"><strong>Please log in.</strong></a></p>
    </div>

{% endblock %}

Autoservice/mysite/autoservice/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Results based on search "{{query}}":</h1>
  </br>
  {% if cars %}
  <ul>
    {% for car in cars %}
      <li>
        <a href="{{ car.id }}">{{car.car_model}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. 0 results found :(</p>
  {% endif %}

  {% endblock %}